language: go

go:
  - 1.10.x

go_import_path: overlord

services:
  - memcached
  - redis
  - docker

install:
  - bash scripts/install-travis-etcd.sh
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install
  - docker pull grokzen/redis-cluster:4.0.9
  - docker run -e "IP=0.0.0.0" -d -p 7000-7007:7000-7007 grokzen/redis-cluster:4.0.9

script:
  - gometalinter --vendor --disable-all --enable=gosimple --enable=golint --enable=vet --enable=ineffassign --enable=unconvert \
    --exclude="by other packages, and that stutters; consider calling this" \
    --skip=proto \
    --skip=vendor \
    --skip=.git \
    --tests ./...
  - ./codecov.sh
  - cd cmd/proxy
  - go build

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
after_script:
- docker stop redis-cluster
- docker rm redis-clust
