language: go

go:
  - 1.9.x
  - 1.10.x

go_import_path: github.com/felixhao/overlord

services:
  - memcached

install:
  - go get github.com/BurntSushi/toml
  - go get github.com/pkg/errors
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install

script:
  - gometalinter --vendor --disable-all --enable=gosimple --enable=golint --enable=vet --enable=ineffassign --enable=unconvert \
    --exclude="by other packages, and that stutters; consider calling this" \
    --skip=proto \
    --skip=vendor \
    --skip=.git \
    --tests ./...
  - cd proxy
  - go test -run=TestProxy
