user = "root"
name = "overlord"
checkpoint = true
master = "172.22.33.167:5050"
executor_url = "http://172.22.33.198:20001/executor"
db_end_point = "http://172.22.33.198:2379"
fail_over = "72h"
role=["sh001"]
